development:
  host: localhost
  database: cpa_development

test:
  host: localhost
  database: cpa_test

# set these environment variables on your prod server
production:
  host: localhost
  database: cpa_production