pid: /var/www/rails/cpa/shared/pids/thin.pid
log: log/thin.log
timeout: 30
max_conns: 1024
socket: /var/www/rails/cpa/shared/thin.sock
no-epoll: true
max_persistent_conns: 512
chdir: /var/www/rails/cpa/current
environment: production
servers: 3
address: 0.0.0.0
daemonize: true